#change the below property as per yml syntax
spring:
    application:
        name: products-service
    datasource:
        url: jdbc:h2:mem:productsdb
        username: sa
        password: sa
        driver-class-name: org.h2.Driver
    h2:
        console:
         enabled: true
    jpa:
        hibernate:
        show-sql: true
        properties:
            hibernate:
            format_sql: true
server:
    port: 4466
